### ISSUE TITLE
Use Canvas API to fetch LTI data and add and remove tools in the course's context

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-app-explorer#160]
- [ ] Creating a class or service that groups together all of the Canvas API interactions
  - [ ] Find a way to use the `canvas-api` library (https://github.com/ucfopen/canvasapi)
  - [ ] Fetch LTI tools available in a course context's navigation
  - [ ] Add LTI tool to navigation
  - [ ] Remove LTI tool from navigation
 - [ ] Add Django Rest Framework (or plain Django) endpoints and views for these actions
 - [ ] Add Swagger UI for API testing and documentation
